### ISSUE TITLE
Reset component resets date-field value with useCurrentDate:true to undefined

### ISSUE THREAD

**Issue by jhyeep** [LifeSG/web-frontend-engine#65]
# Expected Behavior

When a `date-field` component has the property `useCurrentDate: true`, clicking the `reset` component should reset its value back to the current date.

# Current Behavior

If the user has changed the date since the initial render, resetting afterwards works as expected. The bug occurs when the date field has not been modified, in which case resetting will cause the date's value to become `undefined`, while still showing the date input visually. 

Another related visual bug also occurs with `useCurrentDate: false`, where resetting sets the date to `undefined` but the date input is still shown.

# Failure Information (for bugs)

## Steps to Reproduce

1. Render a frontend engine form containing the field components `date-field` and `reset`, with `useCurrentDate: true` for date-field. Add a separate button to log `ref.current.getValues()` to view the current form values
2. Click on the reset button without changing the default date field input
3. The date value becomes `undefined`. (bug)

1. Change `useCurrentDate` to `false`
2. In the form, input any date and click on reset
3. The date input still remains, even though the date value is now `undefined`. (bug)

**Comment by weili-govtech** [comment]
Thanks for reporting, the culprit appears to be a failure to update value via `onChange` when the component mounts: https://github.com/LifeSG/web-frontend-engine/blob/main/src/components/fields/date-field/date-field.tsx#L113

This will be fixed in the https://github.com/LifeSG/web-frontend-engine/pull/66 PR

**Comment by weili-govtech** [comment]
https://github.com/LifeSG/web-frontend-engine/pull/66 has been approved and is slated to be released in `v1.0.0-alpha.5`

**Comment by weili-govtech** [comment]
Fix has been released in `v1.0.0-alpha.5`
- https://github.com/LifeSG/web-frontend-engine/releases/tag/v1.0.0-alpha.5
- https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v100-alpha5
